### ISSUE TITLE
얼마전까지 잘 됐는데 갑자기 안 돼요

### ISSUE THREAD

**Issue by Ajdhsh** [dannydoor/flayer#1]
한 컴퓨터에서만 안 됩니다. 실행은 되지만 첫 화면에서 아무것도 클릭이 안됩니다. 클릭 하려고 커서 가져다 대면 움찔 하는 효과가 있긴 한데 클릭은 안됩니다ㅡㅡ

**Comment by dannydoor** [comment]
크롬으로 실행했는지 확인해보시고, 크롬으로 정상적으로 실행하신게 맞으면 f12 눌러 console 에 들어간 다음 어떤 오류 메세지가 있는지 확인해서 알려주세요. 그리고 localStorage.lastSession = ‘’ 을 입력해보세요. 혹시 그 컴퓨터에서 처음 실행했는데도 그런 문제가 발생하나요?

**Comment by Ajdhsh** [comment]
아니요. 원래 잘 되다가 갑자기 그러네요. 오류 메시지 한 번 확인해보겠습니다. 감사합니다!!

**Comment by Ajdhsh** [comment]
Cannot read properties of undefined(reading 'cloneNode')라고 뜹니다 ㅜㅜ

**Comment by dannydoor** [comment]
혹시 알려드린 해결방법 사용해보셨나요? 아직 해결 안 되셨다면 해당 메세지 아래에 보면 어느 파일의 몇번재 줄에서 문제가 발생했는지 나오는데, 그 부분도 알려주실 수 있나요?

**Comment by Ajdhsh** [comment]
Uncaught TypeError:Cannot read properties of undefined(reading 'cloneNode')
 at bdManager.js:80:34
 at Array.for Each(<anonymus>)
 at Dbmanager.lastSession Importer(dbManager.js:79:37)
 at New DbManager(dbManager.js:33:12)
 at index.html:634:23
이렇게 떠있습니다.

**Comment by dannydoor** [comment]
혹시 정확히 어떤 시점부터 안되기 시작했는지 기억하시나요? db를 업데이트한 이후부터 라던지, 특정 플레이리스트를 틀고 난 뒤부터 라던지…

**Comment by Ajdhsh** [comment]
근무 서는 컴퓨터라 다른 사람들도 잔뜩 있어서 잘 모르겠어요 ㅜㅜ. 제가 마지막으로 썼을 때는 플레이리스트 만들고 백업파일 만들었는데 그 이후로 어떤 일이 있었지는지 모르겠어요 ㅜㅜ.

**Comment by dannydoor** [comment]
제가 마지막에 급하게 넣느라 미처 확인하지 못한 부분도 많고 불완전하게 구현한 기능도 있어서 지금 주어진 정보만으로는 어떤 게 문제가 되는지 파악하기 어렵네요.

일단 임시방편으로 다음과 같이 파일을 수정해주시면 당장의 문제는 해결될 것 같습니다.

1. flayer 폴더의 js 폴더를 찾아 들어가서 dbManager.js 파일을 메모장으로 연결해서 열어주세요.
2. 80번째 줄 쯤에 
` lastSession.queueInfo.queueRepo.forEach((index) => {`
`      let elem = queueArr[index].cloneNode(true); `
`      queueRepoArr.push(elem); `
` });`
와 같은 부분을 찾아주세요.
3. 이 부분을 다음과 같이 고쳐주세요
`lastSession.queueInfo.queueRepo.forEach((index) => {`
`      let elem = queueArr[index] `
`      if (elem) {`
`        queueRepoArr.push(elem.cloneNode(true)); `
`      } `
` }); `
4. 그 아래로 10줄 정도 아래에 다음과 같은 코드를 찾아주세요. queueRepoArr이 아닌 queueArr입니다.
`queueArr.forEach((elem) => queueFragment.append(elem));`
5. 다음과 같이 고쳐주세요.
`queueArr.forEach((elem) => {`
`  if (elem) queueFragment.append(elem) `
`});`
6. 저장하시고 다시 실행해주세요. 이렇게 해도 해결이 안되면 말씀해주세요.

** 대소문자에 유의해주세요
